packages:
  - app
  - common
  - functions

allowBuilds:
  "@firebase/util": false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

onlyBuiltDependencies:
  - esbuild
  - "@firebase/util"
  - protobufjs
  - unrs-resolver
