/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as StorefrontRouteRouteImport } from './routes/_storefront/route'
import { Route as StorefrontIndexRouteImport } from './routes/_storefront/index'
import { Route as SignupSuccessRouteImport } from './routes/signup/success'
import { Route as FamilyTokenRouteImport } from './routes/family/$token'
import { Route as StorefrontCheckoutRouteImport } from './routes/_storefront/checkout'
import { Route as AuthenticatedHelloRouteImport } from './routes/_authenticated/hello'
import { Route as AuthenticatedStaffRouteRouteImport } from './routes/_authenticated/staff/route'
import { Route as AuthenticatedDonorRouteRouteImport } from './routes/_authenticated/donor/route'
import { Route as SignupAdminInviteIdRouteImport } from './routes/signup/admin/$inviteId'
import { Route as FamilyDriveDriveIdRouteImport } from './routes/family/drive/$driveId'
import { Route as FamilyTokenHomeRouteImport } from './routes/family/$token/home'
import { Route as StorefrontChildChildIdRouteImport } from './routes/_storefront/child/$childId'
import { Route as AuthenticatedStaffProfileRouteImport } from './routes/_authenticated/staff/profile'
import { Route as AuthenticatedStaffPendingRouteImport } from './routes/_authenticated/staff/pending'
import { Route as AuthenticatedStaffHomeRouteImport } from './routes/_authenticated/staff/home'
import { Route as AuthenticatedStaffApprovedRouteImport } from './routes/_authenticated/staff/approved'
import { Route as AuthenticatedDonorNotificationsRouteImport } from './routes/_authenticated/donor/notifications'
import { Route as AuthenticatedDonorHomeRouteImport } from './routes/_authenticated/donor/home'
import { Route as AuthenticatedStaffVolunteerRouteRouteImport } from './routes/_authenticated/staff/volunteer/route'
import { Route as AuthenticatedStaffAdminRouteRouteImport } from './routes/_authenticated/staff/admin/route'
import { Route as FamilyDriveDriveIdFormRouteImport } from './routes/family/drive/$driveId/form'
import { Route as FamilyTokenChildChildIdRouteImport } from './routes/family/$token/child/$childId'
import { Route as AuthenticatedStaffReviewFamilyIdRouteImport } from './routes/_authenticated/staff/review/$familyId'
import { Route as AuthenticatedStaffAdminUsersRouteImport } from './routes/_authenticated/staff/admin/users'
import { Route as FamilyDriveDriveIdFormThankYouRouteImport } from './routes/family/drive/$driveId/form/thank-you'
import { Route as FamilyDriveDriveIdFormReviewRouteImport } from './routes/family/drive/$driveId/form/review'
import { Route as FamilyDriveDriveIdFormGiftDetailsRouteImport } from './routes/family/drive/$driveId/form/gift-details'
import { Route as FamilyDriveDriveIdFormGeneralInfoRouteImport } from './routes/family/drive/$driveId/form/general-info'
import { Route as FamilyDriveDriveIdFormConsentRouteImport } from './routes/family/drive/$driveId/form/consent'
import { Route as FamilyDriveDriveIdFormChildrenRouteImport } from './routes/family/drive/$driveId/form/children'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontRouteRoute = StorefrontRouteRouteImport.update({
  id: '/_storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontIndexRoute = StorefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const SignupSuccessRoute = SignupSuccessRouteImport.update({
  id: '/signup/success',
  path: '/signup/success',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTokenRoute = FamilyTokenRouteImport.update({
  id: '/family/$token',
  path: '/family/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StorefrontCheckoutRoute = StorefrontCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const AuthenticatedHelloRoute = AuthenticatedHelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRouteRoute = AuthenticatedStaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonorRouteRoute = AuthenticatedDonorRouteRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SignupAdminInviteIdRoute = SignupAdminInviteIdRouteImport.update({
  id: '/signup/admin/$inviteId',
  path: '/signup/admin/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyDriveDriveIdRoute = FamilyDriveDriveIdRouteImport.update({
  id: '/family/drive/$driveId',
  path: '/family/drive/$driveId',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyTokenHomeRoute = FamilyTokenHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => FamilyTokenRoute,
} as any)
const StorefrontChildChildIdRoute = StorefrontChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => StorefrontRouteRoute,
} as any)
const AuthenticatedStaffProfileRoute =
  AuthenticatedStaffProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffPendingRoute =
  AuthenticatedStaffPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffHomeRoute = AuthenticatedStaffHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedStaffRouteRoute,
} as any)
const AuthenticatedStaffApprovedRoute =
  AuthenticatedStaffApprovedRouteImport.update({
    id: '/approved',
    path: '/approved',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedDonorNotificationsRoute =
  AuthenticatedDonorNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDonorRouteRoute,
  } as any)
const AuthenticatedDonorHomeRoute = AuthenticatedDonorHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedDonorRouteRoute,
} as any)
const AuthenticatedStaffVolunteerRouteRoute =
  AuthenticatedStaffVolunteerRouteRouteImport.update({
    id: '/volunteer',
    path: '/volunteer',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffAdminRouteRoute =
  AuthenticatedStaffAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const FamilyDriveDriveIdFormRoute = FamilyDriveDriveIdFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => FamilyDriveDriveIdRoute,
} as any)
const FamilyTokenChildChildIdRoute = FamilyTokenChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => FamilyTokenRoute,
} as any)
const AuthenticatedStaffReviewFamilyIdRoute =
  AuthenticatedStaffReviewFamilyIdRouteImport.update({
    id: '/review/$familyId',
    path: '/review/$familyId',
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffAdminUsersRoute =
  AuthenticatedStaffAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedStaffAdminRouteRoute,
  } as any)
const FamilyDriveDriveIdFormThankYouRoute =
  FamilyDriveDriveIdFormThankYouRouteImport.update({
    id: '/thank-you',
    path: '/thank-you',
    getParentRoute: () => FamilyDriveDriveIdFormRoute,
  } as any)
const FamilyDriveDriveIdFormReviewRoute =
  FamilyDriveDriveIdFormReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => FamilyDriveDriveIdFormRoute,
  } as any)
const FamilyDriveDriveIdFormGiftDetailsRoute =
  FamilyDriveDriveIdFormGiftDetailsRouteImport.update({
    id: '/gift-details',
    path: '/gift-details',
    getParentRoute: () => FamilyDriveDriveIdFormRoute,
  } as any)
const FamilyDriveDriveIdFormGeneralInfoRoute =
  FamilyDriveDriveIdFormGeneralInfoRouteImport.update({
    id: '/general-info',
    path: '/general-info',
    getParentRoute: () => FamilyDriveDriveIdFormRoute,
  } as any)
const FamilyDriveDriveIdFormConsentRoute =
  FamilyDriveDriveIdFormConsentRouteImport.update({
    id: '/consent',
    path: '/consent',
    getParentRoute: () => FamilyDriveDriveIdFormRoute,
  } as any)
const FamilyDriveDriveIdFormChildrenRoute =
  FamilyDriveDriveIdFormChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => FamilyDriveDriveIdFormRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof StorefrontIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/donor': typeof AuthenticatedDonorRouteRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/hello': typeof AuthenticatedHelloRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/family/$token': typeof FamilyTokenRouteWithChildren
  '/signup/success': typeof SignupSuccessRoute
  '/staff/admin': typeof AuthenticatedStaffAdminRouteRouteWithChildren
  '/staff/volunteer': typeof AuthenticatedStaffVolunteerRouteRoute
  '/donor/home': typeof AuthenticatedDonorHomeRoute
  '/donor/notifications': typeof AuthenticatedDonorNotificationsRoute
  '/staff/approved': typeof AuthenticatedStaffApprovedRoute
  '/staff/home': typeof AuthenticatedStaffHomeRoute
  '/staff/pending': typeof AuthenticatedStaffPendingRoute
  '/staff/profile': typeof AuthenticatedStaffProfileRoute
  '/child/$childId': typeof StorefrontChildChildIdRoute
  '/family/$token/home': typeof FamilyTokenHomeRoute
  '/family/drive/$driveId': typeof FamilyDriveDriveIdRouteWithChildren
  '/signup/admin/$inviteId': typeof SignupAdminInviteIdRoute
  '/staff/admin/users': typeof AuthenticatedStaffAdminUsersRoute
  '/staff/review/$familyId': typeof AuthenticatedStaffReviewFamilyIdRoute
  '/family/$token/child/$childId': typeof FamilyTokenChildChildIdRoute
  '/family/drive/$driveId/form': typeof FamilyDriveDriveIdFormRouteWithChildren
  '/family/drive/$driveId/form/children': typeof FamilyDriveDriveIdFormChildrenRoute
  '/family/drive/$driveId/form/consent': typeof FamilyDriveDriveIdFormConsentRoute
  '/family/drive/$driveId/form/general-info': typeof FamilyDriveDriveIdFormGeneralInfoRoute
  '/family/drive/$driveId/form/gift-details': typeof FamilyDriveDriveIdFormGiftDetailsRoute
  '/family/drive/$driveId/form/review': typeof FamilyDriveDriveIdFormReviewRoute
  '/family/drive/$driveId/form/thank-you': typeof FamilyDriveDriveIdFormThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof StorefrontIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/donor': typeof AuthenticatedDonorRouteRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/hello': typeof AuthenticatedHelloRoute
  '/checkout': typeof StorefrontCheckoutRoute
  '/family/$token': typeof FamilyTokenRouteWithChildren
  '/signup/success': typeof SignupSuccessRoute
  '/staff/admin': typeof AuthenticatedStaffAdminRouteRouteWithChildren
  '/staff/volunteer': typeof AuthenticatedStaffVolunteerRouteRoute
  '/donor/home': typeof AuthenticatedDonorHomeRoute
  '/donor/notifications': typeof AuthenticatedDonorNotificationsRoute
  '/staff/approved': typeof AuthenticatedStaffApprovedRoute
  '/staff/home': typeof AuthenticatedStaffHomeRoute
  '/staff/pending': typeof AuthenticatedStaffPendingRoute
  '/staff/profile': typeof AuthenticatedStaffProfileRoute
  '/child/$childId': typeof StorefrontChildChildIdRoute
  '/family/$token/home': typeof FamilyTokenHomeRoute
  '/family/drive/$driveId': typeof FamilyDriveDriveIdRouteWithChildren
  '/signup/admin/$inviteId': typeof SignupAdminInviteIdRoute
  '/staff/admin/users': typeof AuthenticatedStaffAdminUsersRoute
  '/staff/review/$familyId': typeof AuthenticatedStaffReviewFamilyIdRoute
  '/family/$token/child/$childId': typeof FamilyTokenChildChildIdRoute
  '/family/drive/$driveId/form': typeof FamilyDriveDriveIdFormRouteWithChildren
  '/family/drive/$driveId/form/children': typeof FamilyDriveDriveIdFormChildrenRoute
  '/family/drive/$driveId/form/consent': typeof FamilyDriveDriveIdFormConsentRoute
  '/family/drive/$driveId/form/general-info': typeof FamilyDriveDriveIdFormGeneralInfoRoute
  '/family/drive/$driveId/form/gift-details': typeof FamilyDriveDriveIdFormGiftDetailsRoute
  '/family/drive/$driveId/form/review': typeof FamilyDriveDriveIdFormReviewRoute
  '/family/drive/$driveId/form/thank-you': typeof FamilyDriveDriveIdFormThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_storefront': typeof StorefrontRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/donor': typeof AuthenticatedDonorRouteRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteRouteWithChildren
  '/_authenticated/hello': typeof AuthenticatedHelloRoute
  '/_storefront/checkout': typeof StorefrontCheckoutRoute
  '/family/$token': typeof FamilyTokenRouteWithChildren
  '/signup/success': typeof SignupSuccessRoute
  '/_storefront/': typeof StorefrontIndexRoute
  '/_authenticated/staff/admin': typeof AuthenticatedStaffAdminRouteRouteWithChildren
  '/_authenticated/staff/volunteer': typeof AuthenticatedStaffVolunteerRouteRoute
  '/_authenticated/donor/home': typeof AuthenticatedDonorHomeRoute
  '/_authenticated/donor/notifications': typeof AuthenticatedDonorNotificationsRoute
  '/_authenticated/staff/approved': typeof AuthenticatedStaffApprovedRoute
  '/_authenticated/staff/home': typeof AuthenticatedStaffHomeRoute
  '/_authenticated/staff/pending': typeof AuthenticatedStaffPendingRoute
  '/_authenticated/staff/profile': typeof AuthenticatedStaffProfileRoute
  '/_storefront/child/$childId': typeof StorefrontChildChildIdRoute
  '/family/$token/home': typeof FamilyTokenHomeRoute
  '/family/drive/$driveId': typeof FamilyDriveDriveIdRouteWithChildren
  '/signup/admin/$inviteId': typeof SignupAdminInviteIdRoute
  '/_authenticated/staff/admin/users': typeof AuthenticatedStaffAdminUsersRoute
  '/_authenticated/staff/review/$familyId': typeof AuthenticatedStaffReviewFamilyIdRoute
  '/family/$token/child/$childId': typeof FamilyTokenChildChildIdRoute
  '/family/drive/$driveId/form': typeof FamilyDriveDriveIdFormRouteWithChildren
  '/family/drive/$driveId/form/children': typeof FamilyDriveDriveIdFormChildrenRoute
  '/family/drive/$driveId/form/consent': typeof FamilyDriveDriveIdFormConsentRoute
  '/family/drive/$driveId/form/general-info': typeof FamilyDriveDriveIdFormGeneralInfoRoute
  '/family/drive/$driveId/form/gift-details': typeof FamilyDriveDriveIdFormGiftDetailsRoute
  '/family/drive/$driveId/form/review': typeof FamilyDriveDriveIdFormReviewRoute
  '/family/drive/$driveId/form/thank-you': typeof FamilyDriveDriveIdFormThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/donor'
    | '/staff'
    | '/hello'
    | '/checkout'
    | '/family/$token'
    | '/signup/success'
    | '/staff/admin'
    | '/staff/volunteer'
    | '/donor/home'
    | '/donor/notifications'
    | '/staff/approved'
    | '/staff/home'
    | '/staff/pending'
    | '/staff/profile'
    | '/child/$childId'
    | '/family/$token/home'
    | '/family/drive/$driveId'
    | '/signup/admin/$inviteId'
    | '/staff/admin/users'
    | '/staff/review/$familyId'
    | '/family/$token/child/$childId'
    | '/family/drive/$driveId/form'
    | '/family/drive/$driveId/form/children'
    | '/family/drive/$driveId/form/consent'
    | '/family/drive/$driveId/form/general-info'
    | '/family/drive/$driveId/form/gift-details'
    | '/family/drive/$driveId/form/review'
    | '/family/drive/$driveId/form/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/donor'
    | '/staff'
    | '/hello'
    | '/checkout'
    | '/family/$token'
    | '/signup/success'
    | '/staff/admin'
    | '/staff/volunteer'
    | '/donor/home'
    | '/donor/notifications'
    | '/staff/approved'
    | '/staff/home'
    | '/staff/pending'
    | '/staff/profile'
    | '/child/$childId'
    | '/family/$token/home'
    | '/family/drive/$driveId'
    | '/signup/admin/$inviteId'
    | '/staff/admin/users'
    | '/staff/review/$familyId'
    | '/family/$token/child/$childId'
    | '/family/drive/$driveId/form'
    | '/family/drive/$driveId/form/children'
    | '/family/drive/$driveId/form/consent'
    | '/family/drive/$driveId/form/general-info'
    | '/family/drive/$driveId/form/gift-details'
    | '/family/drive/$driveId/form/review'
    | '/family/drive/$driveId/form/thank-you'
  id:
    | '__root__'
    | '/_storefront'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/donor'
    | '/_authenticated/staff'
    | '/_authenticated/hello'
    | '/_storefront/checkout'
    | '/family/$token'
    | '/signup/success'
    | '/_storefront/'
    | '/_authenticated/staff/admin'
    | '/_authenticated/staff/volunteer'
    | '/_authenticated/donor/home'
    | '/_authenticated/donor/notifications'
    | '/_authenticated/staff/approved'
    | '/_authenticated/staff/home'
    | '/_authenticated/staff/pending'
    | '/_authenticated/staff/profile'
    | '/_storefront/child/$childId'
    | '/family/$token/home'
    | '/family/drive/$driveId'
    | '/signup/admin/$inviteId'
    | '/_authenticated/staff/admin/users'
    | '/_authenticated/staff/review/$familyId'
    | '/family/$token/child/$childId'
    | '/family/drive/$driveId/form'
    | '/family/drive/$driveId/form/children'
    | '/family/drive/$driveId/form/consent'
    | '/family/drive/$driveId/form/general-info'
    | '/family/drive/$driveId/form/gift-details'
    | '/family/drive/$driveId/form/review'
    | '/family/drive/$driveId/form/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StorefrontRouteRoute: typeof StorefrontRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  FamilyTokenRoute: typeof FamilyTokenRouteWithChildren
  SignupSuccessRoute: typeof SignupSuccessRoute
  FamilyDriveDriveIdRoute: typeof FamilyDriveDriveIdRouteWithChildren
  SignupAdminInviteIdRoute: typeof SignupAdminInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront': {
      id: '/_storefront'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront/': {
      id: '/_storefront/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StorefrontIndexRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/signup/success': {
      id: '/signup/success'
      path: '/signup/success'
      fullPath: '/signup/success'
      preLoaderRoute: typeof SignupSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/$token': {
      id: '/family/$token'
      path: '/family/$token'
      fullPath: '/family/$token'
      preLoaderRoute: typeof FamilyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storefront/checkout': {
      id: '/_storefront/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StorefrontCheckoutRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_authenticated/hello': {
      id: '/_authenticated/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof AuthenticatedHelloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donor': {
      id: '/_authenticated/donor'
      path: '/donor'
      fullPath: '/donor'
      preLoaderRoute: typeof AuthenticatedDonorRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/signup/admin/$inviteId': {
      id: '/signup/admin/$inviteId'
      path: '/signup/admin/$inviteId'
      fullPath: '/signup/admin/$inviteId'
      preLoaderRoute: typeof SignupAdminInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/drive/$driveId': {
      id: '/family/drive/$driveId'
      path: '/family/drive/$driveId'
      fullPath: '/family/drive/$driveId'
      preLoaderRoute: typeof FamilyDriveDriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family/$token/home': {
      id: '/family/$token/home'
      path: '/home'
      fullPath: '/family/$token/home'
      preLoaderRoute: typeof FamilyTokenHomeRouteImport
      parentRoute: typeof FamilyTokenRoute
    }
    '/_storefront/child/$childId': {
      id: '/_storefront/child/$childId'
      path: '/child/$childId'
      fullPath: '/child/$childId'
      preLoaderRoute: typeof StorefrontChildChildIdRouteImport
      parentRoute: typeof StorefrontRouteRoute
    }
    '/_authenticated/staff/profile': {
      id: '/_authenticated/staff/profile'
      path: '/profile'
      fullPath: '/staff/profile'
      preLoaderRoute: typeof AuthenticatedStaffProfileRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/pending': {
      id: '/_authenticated/staff/pending'
      path: '/pending'
      fullPath: '/staff/pending'
      preLoaderRoute: typeof AuthenticatedStaffPendingRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/home': {
      id: '/_authenticated/staff/home'
      path: '/home'
      fullPath: '/staff/home'
      preLoaderRoute: typeof AuthenticatedStaffHomeRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/approved': {
      id: '/_authenticated/staff/approved'
      path: '/approved'
      fullPath: '/staff/approved'
      preLoaderRoute: typeof AuthenticatedStaffApprovedRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/donor/notifications': {
      id: '/_authenticated/donor/notifications'
      path: '/notifications'
      fullPath: '/donor/notifications'
      preLoaderRoute: typeof AuthenticatedDonorNotificationsRouteImport
      parentRoute: typeof AuthenticatedDonorRouteRoute
    }
    '/_authenticated/donor/home': {
      id: '/_authenticated/donor/home'
      path: '/home'
      fullPath: '/donor/home'
      preLoaderRoute: typeof AuthenticatedDonorHomeRouteImport
      parentRoute: typeof AuthenticatedDonorRouteRoute
    }
    '/_authenticated/staff/volunteer': {
      id: '/_authenticated/staff/volunteer'
      path: '/volunteer'
      fullPath: '/staff/volunteer'
      preLoaderRoute: typeof AuthenticatedStaffVolunteerRouteRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/admin': {
      id: '/_authenticated/staff/admin'
      path: '/admin'
      fullPath: '/staff/admin'
      preLoaderRoute: typeof AuthenticatedStaffAdminRouteRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/family/drive/$driveId/form': {
      id: '/family/drive/$driveId/form'
      path: '/form'
      fullPath: '/family/drive/$driveId/form'
      preLoaderRoute: typeof FamilyDriveDriveIdFormRouteImport
      parentRoute: typeof FamilyDriveDriveIdRoute
    }
    '/family/$token/child/$childId': {
      id: '/family/$token/child/$childId'
      path: '/child/$childId'
      fullPath: '/family/$token/child/$childId'
      preLoaderRoute: typeof FamilyTokenChildChildIdRouteImport
      parentRoute: typeof FamilyTokenRoute
    }
    '/_authenticated/staff/review/$familyId': {
      id: '/_authenticated/staff/review/$familyId'
      path: '/review/$familyId'
      fullPath: '/staff/review/$familyId'
      preLoaderRoute: typeof AuthenticatedStaffReviewFamilyIdRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    '/_authenticated/staff/admin/users': {
      id: '/_authenticated/staff/admin/users'
      path: '/users'
      fullPath: '/staff/admin/users'
      preLoaderRoute: typeof AuthenticatedStaffAdminUsersRouteImport
      parentRoute: typeof AuthenticatedStaffAdminRouteRoute
    }
    '/family/drive/$driveId/form/thank-you': {
      id: '/family/drive/$driveId/form/thank-you'
      path: '/thank-you'
      fullPath: '/family/drive/$driveId/form/thank-you'
      preLoaderRoute: typeof FamilyDriveDriveIdFormThankYouRouteImport
      parentRoute: typeof FamilyDriveDriveIdFormRoute
    }
    '/family/drive/$driveId/form/review': {
      id: '/family/drive/$driveId/form/review'
      path: '/review'
      fullPath: '/family/drive/$driveId/form/review'
      preLoaderRoute: typeof FamilyDriveDriveIdFormReviewRouteImport
      parentRoute: typeof FamilyDriveDriveIdFormRoute
    }
    '/family/drive/$driveId/form/gift-details': {
      id: '/family/drive/$driveId/form/gift-details'
      path: '/gift-details'
      fullPath: '/family/drive/$driveId/form/gift-details'
      preLoaderRoute: typeof FamilyDriveDriveIdFormGiftDetailsRouteImport
      parentRoute: typeof FamilyDriveDriveIdFormRoute
    }
    '/family/drive/$driveId/form/general-info': {
      id: '/family/drive/$driveId/form/general-info'
      path: '/general-info'
      fullPath: '/family/drive/$driveId/form/general-info'
      preLoaderRoute: typeof FamilyDriveDriveIdFormGeneralInfoRouteImport
      parentRoute: typeof FamilyDriveDriveIdFormRoute
    }
    '/family/drive/$driveId/form/consent': {
      id: '/family/drive/$driveId/form/consent'
      path: '/consent'
      fullPath: '/family/drive/$driveId/form/consent'
      preLoaderRoute: typeof FamilyDriveDriveIdFormConsentRouteImport
      parentRoute: typeof FamilyDriveDriveIdFormRoute
    }
    '/family/drive/$driveId/form/children': {
      id: '/family/drive/$driveId/form/children'
      path: '/children'
      fullPath: '/family/drive/$driveId/form/children'
      preLoaderRoute: typeof FamilyDriveDriveIdFormChildrenRouteImport
      parentRoute: typeof FamilyDriveDriveIdFormRoute
    }
  }
}

interface StorefrontRouteRouteChildren {
  StorefrontCheckoutRoute: typeof StorefrontCheckoutRoute
  StorefrontIndexRoute: typeof StorefrontIndexRoute
  StorefrontChildChildIdRoute: typeof StorefrontChildChildIdRoute
}

const StorefrontRouteRouteChildren: StorefrontRouteRouteChildren = {
  StorefrontCheckoutRoute: StorefrontCheckoutRoute,
  StorefrontIndexRoute: StorefrontIndexRoute,
  StorefrontChildChildIdRoute: StorefrontChildChildIdRoute,
}

const StorefrontRouteRouteWithChildren = StorefrontRouteRoute._addFileChildren(
  StorefrontRouteRouteChildren,
)

interface AuthenticatedDonorRouteRouteChildren {
  AuthenticatedDonorHomeRoute: typeof AuthenticatedDonorHomeRoute
  AuthenticatedDonorNotificationsRoute: typeof AuthenticatedDonorNotificationsRoute
}

const AuthenticatedDonorRouteRouteChildren: AuthenticatedDonorRouteRouteChildren =
  {
    AuthenticatedDonorHomeRoute: AuthenticatedDonorHomeRoute,
    AuthenticatedDonorNotificationsRoute: AuthenticatedDonorNotificationsRoute,
  }

const AuthenticatedDonorRouteRouteWithChildren =
  AuthenticatedDonorRouteRoute._addFileChildren(
    AuthenticatedDonorRouteRouteChildren,
  )

interface AuthenticatedStaffAdminRouteRouteChildren {
  AuthenticatedStaffAdminUsersRoute: typeof AuthenticatedStaffAdminUsersRoute
}

const AuthenticatedStaffAdminRouteRouteChildren: AuthenticatedStaffAdminRouteRouteChildren =
  {
    AuthenticatedStaffAdminUsersRoute: AuthenticatedStaffAdminUsersRoute,
  }

const AuthenticatedStaffAdminRouteRouteWithChildren =
  AuthenticatedStaffAdminRouteRoute._addFileChildren(
    AuthenticatedStaffAdminRouteRouteChildren,
  )

interface AuthenticatedStaffRouteRouteChildren {
  AuthenticatedStaffAdminRouteRoute: typeof AuthenticatedStaffAdminRouteRouteWithChildren
  AuthenticatedStaffVolunteerRouteRoute: typeof AuthenticatedStaffVolunteerRouteRoute
  AuthenticatedStaffApprovedRoute: typeof AuthenticatedStaffApprovedRoute
  AuthenticatedStaffHomeRoute: typeof AuthenticatedStaffHomeRoute
  AuthenticatedStaffPendingRoute: typeof AuthenticatedStaffPendingRoute
  AuthenticatedStaffProfileRoute: typeof AuthenticatedStaffProfileRoute
  AuthenticatedStaffReviewFamilyIdRoute: typeof AuthenticatedStaffReviewFamilyIdRoute
}

const AuthenticatedStaffRouteRouteChildren: AuthenticatedStaffRouteRouteChildren =
  {
    AuthenticatedStaffAdminRouteRoute:
      AuthenticatedStaffAdminRouteRouteWithChildren,
    AuthenticatedStaffVolunteerRouteRoute:
      AuthenticatedStaffVolunteerRouteRoute,
    AuthenticatedStaffApprovedRoute: AuthenticatedStaffApprovedRoute,
    AuthenticatedStaffHomeRoute: AuthenticatedStaffHomeRoute,
    AuthenticatedStaffPendingRoute: AuthenticatedStaffPendingRoute,
    AuthenticatedStaffProfileRoute: AuthenticatedStaffProfileRoute,
    AuthenticatedStaffReviewFamilyIdRoute:
      AuthenticatedStaffReviewFamilyIdRoute,
  }

const AuthenticatedStaffRouteRouteWithChildren =
  AuthenticatedStaffRouteRoute._addFileChildren(
    AuthenticatedStaffRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDonorRouteRoute: typeof AuthenticatedDonorRouteRouteWithChildren
  AuthenticatedStaffRouteRoute: typeof AuthenticatedStaffRouteRouteWithChildren
  AuthenticatedHelloRoute: typeof AuthenticatedHelloRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDonorRouteRoute: AuthenticatedDonorRouteRouteWithChildren,
  AuthenticatedStaffRouteRoute: AuthenticatedStaffRouteRouteWithChildren,
  AuthenticatedHelloRoute: AuthenticatedHelloRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface FamilyTokenRouteChildren {
  FamilyTokenHomeRoute: typeof FamilyTokenHomeRoute
  FamilyTokenChildChildIdRoute: typeof FamilyTokenChildChildIdRoute
}

const FamilyTokenRouteChildren: FamilyTokenRouteChildren = {
  FamilyTokenHomeRoute: FamilyTokenHomeRoute,
  FamilyTokenChildChildIdRoute: FamilyTokenChildChildIdRoute,
}

const FamilyTokenRouteWithChildren = FamilyTokenRoute._addFileChildren(
  FamilyTokenRouteChildren,
)

interface FamilyDriveDriveIdFormRouteChildren {
  FamilyDriveDriveIdFormChildrenRoute: typeof FamilyDriveDriveIdFormChildrenRoute
  FamilyDriveDriveIdFormConsentRoute: typeof FamilyDriveDriveIdFormConsentRoute
  FamilyDriveDriveIdFormGeneralInfoRoute: typeof FamilyDriveDriveIdFormGeneralInfoRoute
  FamilyDriveDriveIdFormGiftDetailsRoute: typeof FamilyDriveDriveIdFormGiftDetailsRoute
  FamilyDriveDriveIdFormReviewRoute: typeof FamilyDriveDriveIdFormReviewRoute
  FamilyDriveDriveIdFormThankYouRoute: typeof FamilyDriveDriveIdFormThankYouRoute
}

const FamilyDriveDriveIdFormRouteChildren: FamilyDriveDriveIdFormRouteChildren =
  {
    FamilyDriveDriveIdFormChildrenRoute: FamilyDriveDriveIdFormChildrenRoute,
    FamilyDriveDriveIdFormConsentRoute: FamilyDriveDriveIdFormConsentRoute,
    FamilyDriveDriveIdFormGeneralInfoRoute:
      FamilyDriveDriveIdFormGeneralInfoRoute,
    FamilyDriveDriveIdFormGiftDetailsRoute:
      FamilyDriveDriveIdFormGiftDetailsRoute,
    FamilyDriveDriveIdFormReviewRoute: FamilyDriveDriveIdFormReviewRoute,
    FamilyDriveDriveIdFormThankYouRoute: FamilyDriveDriveIdFormThankYouRoute,
  }

const FamilyDriveDriveIdFormRouteWithChildren =
  FamilyDriveDriveIdFormRoute._addFileChildren(
    FamilyDriveDriveIdFormRouteChildren,
  )

interface FamilyDriveDriveIdRouteChildren {
  FamilyDriveDriveIdFormRoute: typeof FamilyDriveDriveIdFormRouteWithChildren
}

const FamilyDriveDriveIdRouteChildren: FamilyDriveDriveIdRouteChildren = {
  FamilyDriveDriveIdFormRoute: FamilyDriveDriveIdFormRouteWithChildren,
}

const FamilyDriveDriveIdRouteWithChildren =
  FamilyDriveDriveIdRoute._addFileChildren(FamilyDriveDriveIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StorefrontRouteRoute: StorefrontRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  FamilyTokenRoute: FamilyTokenRouteWithChildren,
  SignupSuccessRoute: SignupSuccessRoute,
  FamilyDriveDriveIdRoute: FamilyDriveDriveIdRouteWithChildren,
  SignupAdminInviteIdRoute: SignupAdminInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
